---
services:
  kube-openvscode:
    image: ghcr.io/prmiguel/kube-openvscode-server:main
    container_name: kube-openvscode
   # network_mode: bridge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_PASSWORD=Password!
    # volumes:
      # - <your_kube_config>:/config/.kube/config
      # - <your_kube_code>:/code:rw
    ports:
      - 3000:3000
      # - 9080-9090:9080-9090
    restart: unless-stopped
