---
services:
  kube-openvscode:
    image: ghcr.io/prmiguel/kube-openvscode-server:main
    container_name: kube-openvscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - CONNECTION_TOKEN= #optional
      # - CONNECTION_SECRET= #optional
      - SUDO_PASSWORD=Password!
      # - SUDO_PASSWORD_HASH= #optional
    # volumes:
      # - code:/code:rw
      # - /path/to/appdata/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
